/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author user
 */
public class GDQLBanDoc extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form GDQLBanDoc
     */
    public GDQLBanDoc() {
        initComponents();
        btnChinhSuaTTBanDoc.addActionListener(this);
        btnGiaHanTheBanDoc.addActionListener(this);
        btnHuyTheBanDoc.addActionListener(this);
        btnThemBanDoc.addActionListener(this);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnThemBanDoc = new javax.swing.JButton();
        btnChinhSuaTTBanDoc = new javax.swing.JButton();
        btnGiaHanTheBanDoc = new javax.swing.JButton();
        btnHuyTheBanDoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Quan ly ban doc");

        btnThemBanDoc.setText("Them moi");

        btnChinhSuaTTBanDoc.setText("Chinh su TT ban doc");

        btnGiaHanTheBanDoc.setText("Gia han the");

        btnHuyTheBanDoc.setText("Huy the ban doc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnChinhSuaTTBanDoc)
                            .addComponent(btnThemBanDoc)
                            .addComponent(btnGiaHanTheBanDoc)
                            .addComponent(btnHuyTheBanDoc))))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(btnThemBanDoc)
                .addGap(34, 34, 34)
                .addComponent(btnChinhSuaTTBanDoc)
                .addGap(38, 38, 38)
                .addComponent(btnGiaHanTheBanDoc)
                .addGap(38, 38, 38)
                .addComponent(btnHuyTheBanDoc)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDQLBanDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDQLBanDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDQLBanDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDQLBanDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GDQLBanDoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChinhSuaTTBanDoc;
    private javax.swing.JButton btnGiaHanTheBanDoc;
    private javax.swing.JButton btnHuyTheBanDoc;
    private javax.swing.JButton btnThemBanDoc;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(btnThemBanDoc)){
            btnThemBanDocClick();
        }else if(e.getSource().equals(btnChinhSuaTTBanDoc)){
            btnChinhSuaTTBanDocClick();
        }else if(e.getSource().equals(btnGiaHanTheBanDoc)){
            btnGiaHanTheBanDocClick();
        }
        else btnHuyTheBanDocClick();
    }
    
    public void btnThemBanDocClick(){
        new GDThemBanDoc().setVisible(true);
        this.dispose();
    }
    public void btnHuyTheBanDocClick(){
        
    }
    public void btnChinhSuaTTBanDocClick(){
        
    }
    public void btnGiaHanTheBanDocClick(){
        
    }
}
